<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>steaminv</AssemblyName>
    <RootNamespace>SteamInvValue.Cli</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SteamInvValue.Core\SteamInvValue.Core.csproj" />
  </ItemGroup>
</Project>
